In [6]:

import numpy as np

# We create a 5 x 5 ndarray that contains integers from 0 to 24
X = np.arange(25).reshape(5, 5)

print('Original X = \n', X)

#Boolean indexing to select elements in X:
print('The elements in X that are greater than 10:', X[X > 10])
print('The elements in X that less than or equal to 7:', X[X <= 7])
print('The elements in X that are between 10 and 17:', X[(X > 10) & (X < 17)])

#Boolean indexing to assign the elements that are between 10 and 17 the value of -2
X[(X > 10) & (X < 17)] = -2

print('X = \n', X)

Original X = 
 [[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]
The elements in X that are greater than 10: [11 12 13 14 15 16 17 18 19 20 21 22 23 24]
The elements in X that less than or equal to 7: [0 1 2 3 4 5 6 7]
The elements in X that are between 10 and 17: [11 12 13 14 15 16]
X = 
 [[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 -2 -2 -2 -2]
 [-2 -2 17 18 19]
 [20 21 22 23 24]]
