In [6]:
import numpy as np
# Create a 4 x 5 ndarray that contains integers from 0 to 19
X = np.arange(20).reshape(4, 5)

print('X = \n', X)

# We select all the elements that are in the 2nd through 4th rows and in the 3rd to 5th columns
Z = X[1:4,2:5]

print('Z = \n', Z)

# We can select the same elements as above using method 2
W = X[1:,2:5]

print('W = \n', W)

# We select all the elements that are in the 1st through 3rd rows and in the 3rd to 4th columns
Y = X[:3,2:5]

print('Y = \n', Y)

# We select all the elements in the 3rd row
v = X[2,:]

print('v = ', v)

# We select all the elements in the 3rd column
q = X[:,2]

print('q =\n ', q)

# We select all the elements in the 3rd column but return a rank 2 ndarray
R = X[:,2:3]

print('R = \n', R)

X = 
 [[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]]
Z = 
 [[ 7  8  9]
 [12 13 14]
 [17 18 19]]
W = 
 [[ 7  8  9]
 [12 13 14]
 [17 18 19]]
Y = 
 [[ 2  3  4]
 [ 7  8  9]
 [12 13 14]]
v =  [10 11 12 13 14]
q =
  [ 2  7 12 17]
R = 
 [[ 2]
 [ 7]
 [12]
 [17]]
